In [1]:
import numpy as np

In [98]:
interval = [-5.12, 5.12]
interval = [2, 5]
print(interval)

[2, 5]


In [61]:
def rastrigin(X, A = 10):
    
    """ Rastrigin function. """
    
    n = len(X)
    Y = A*n + sum([np.square(x) - A*np.cos(2*np.pi*x) for x in X])
    
    return Y

In [226]:
def decoding(B, l, interval):
    
    """ Decoding each binary solution to a floating point representation. """
    
    n = int(len(B)/l)
    X = np.zeros((n,))
    
    # The interval between adjacent values
    delta = (interval[1] - interval[0])/(np.power(2,l)-1)  
    
    # For each variable b in B
    for i in range(n):
        b = B[l*i:l*(i+1)]
        X[i] = interval[0] + delta * sum([b[k]*np.power(2,(l-k-1)) for k in range(l)])

    return X

In [233]:
b1 = [0, 0, 0, 1, 0, 1, 1, 0, 1, 1]
b2 = np.zeros((10,))
b3 = np.ones((10,))
B = np.vstack([b1, b2, b3])
print(B, '\n')
B = B.reshape((30,))
print(B)

[[0. 0. 0. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [234]:
X = decoding(B, l=10, interval=interval)
print(X)

[2.26686217 2.         5.        ]


In [ ]:
def encoding(X, l):
    
    """ Encoding each real solution to a binary representation. """
    
    n = len(X)
    
    # For each variable X[i]
    for i in range(n):
        